include_guard(GLOBAL)

message(STATUS "")
message(STATUS "Expp Configuration Summary")
message(STATUS "================================")
message(STATUS "Version:             ${PROJECT_VERSION}")
message(STATUS "Build type:          ${CMAKE_BUILD_TYPE}")
message(STATUS "C++ Compiler:        ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "Disable exceptions:  ${EXPP_DISABLE_EXCEPTIONS}")
message(STATUS "Build tests:         ${EXPP_BUILD_TESTS}")
message(STATUS "Build examples:      ${EXPP_BUILD_EXAMPLES}")
message(STATUS "Build benchmarks:    ${EXPP_ENABLE_BENCHMARKS}")
message(STATUS "Sanitizers:          ${EXPP_ENABLE_SANITIZERS}")
message(STATUS "clang-tidy:          ${EXPP_ENABLE_CLANG_TIDY}")
message(STATUS "cppcheck:            ${EXPP_ENABLE_CPPCHECK}")
message(STATUS "libmagic:            ${EXPP_LIBMAGIC_COMPILED_IN}")
message(STATUS "libarchive:          ${EXPP_LIBARCHIVE_COMPILED_IN}")
message(STATUS "Tree-sitter:         ${EXPP_TREE_SITTER_COMPILED_IN}")
message(STATUS "Terminal images:     ${EXPP_ENABLE_TERMINAL_IMAGES}")
message(STATUS "libgit2:             ${EXPP_LIBGIT2_COMPILED_IN}")
message(STATUS "")
